### ISSUE TITLE
v2.x throwing type errors and errors on build

### ISSUE THREAD

**Issue by treyhuffine** [sendinblue/APIv3-typescript-library#16] opened 2020-12-06 00:19 UTC
Upgraded from 1.2.1 to 2.0.2 and am getting errors. Doing pretty simple things like addings emails to contacts and sending a transactional email for account creation. The only change I made in my code was switching to the new transactional class name.

<img width="1099" alt="Screen Shot 2020-12-05 at 6 02 20 PM" src="https://user-images.githubusercontent.com/11709986/101267984-2429c680-3724-11eb-8968-431967d1de89.png">
<img width="1386" alt="Screen Shot 2020-12-05 at 6 02 02 PM" src="https://user-images.githubusercontent.com/11709986/101267986-27bd4d80-3724-11eb-9087-cc3de58cc16d.png">

**Comment by aayush-sib** [comment] 2020-12-10 05:20
Hi @treyhuffine 
Try changing the value of `module` in `tsconfig.json` to `commonjs`, it might help.

**Comment by gmencz** [comment] 2020-12-18 21:27
I'm also having this issue when running the build phase with NextJS, it's not an option to change the value of `module` in `tsconfig.json` because NextJS doesn't use that option during build.

**Comment by treyhuffine** [comment] 2020-12-19 13:53
I'm using NextJS as well and seeing this issue. This is the only package I'm using that causes this problem, so I would imagine it could be resolved in the build phase to make it a more generally usable NPM package.

@gmencz I've downgraded to the 1.x package which still works if you need a quick fix.

**Comment by gmencz** [comment] 2020-12-19 16:37
Thanks @treyhuffine downgrading seems to have fixed it, though I had to `// @ts-ignore` a bunch of typescript issues that I did not have with 2.x, at least now the build passes.

**Comment by matiasbastos** [comment] 2021-01-18 16:52
Same issue here.  Sadly had to downgrade to 1.x and hack some types to make it work 😞

**Comment by ThomasP1988** [comment] 2021-02-01 07:01
3 releases after, the code is still not linted, and couldnt be used by lot of people, can you just lint your code please?

**Comment by nickfla1** [comment] 2021-02-03 10:50
Same issue here, using NextJSl. This should really be considered a priority issue.
Let me know if you would accept incoming PRs.

**Comment by aayush-sib** [comment] 2021-02-03 11:13
Hi @nickfla1 
Thanks for helping out. You can raise the PR we will definitely look into it. 

Sorry for the inconvenience, we are not able to replicate the issue at our end.

**Comment by lorenzogm** [comment] 2021-02-19 20:42
I have created a PR @aayush-sib to fix this issue #23 

Could you mind to review it and release it?

**Comment by aayush-sib** [comment] 2021-02-22 05:59
Hi @treyhuffine @gmencz @matiasbastos @ThomasP1988 @nickfla1 Can you all please confirm if the changes are working fine in your projects?

**Comment by matiasbastos** [comment] 2021-02-22 08:41
I'll give it a test later, but from the top of my head, I remember having a lot of unused imports giving error on build...

**Comment by aayush-sib** [comment] 2021-03-03 08:25
Hi @lorenzogm @matiasbastos 
I see there are 2 open PRs regarding this issue. Can you please close one PR so that I can proceed with the review process of the final PR?
Thanks!

**Comment by lorenzogm** [comment] 2021-03-03 11:56
My PR #23 is to fix the errors described above in this issue. So maybe start reviewing that one.

@matiasbastos added something else that probably needs to be fixed as well, but it's not what we discussed in this issue.

**Comment by matiasbastos** [comment] 2021-03-04 09:02
Well, #24 is also related to type errors on build but can create a new issue for my PR.

**Comment by aayush-sib** [comment] 2021-03-04 09:14
Hi @matiasbastos 
You can create a separate issue for your PR.

**Comment by matiasbastos** [comment] 2021-03-08 17:05
@aayush-sib there you go https://github.com/sendinblue/APIv3-typescript-library/issues/25

**Comment by aayush-sib** [comment] 2021-07-14 07:04
Hi 

I have released a beta tag https://www.npmjs.com/package/sib-api-v3-typescript/v/2.2.3-beta.1 for this. Can you please check if this is working well on your side?

**Comment by rennehir** [comment] 2023-03-22 11:55
No activity in this for a looong time... I just happened to stumble on this issue. I got it fixed by using `@sendinblue/client@3.3.1` instead of the package called `sib-api-v3-typescript`. They seem to be the same but the latter hasn't been updated in a long long time.

**Comment by aayush-sib** [comment] 2023-04-22 08:24
Hi 
Our new package can be found on `@sendinblue/client`. As @rennehir mentioned the issue is not there in the latest version, so closing this issue.

**Closed by aayush-sib** 2023-04-22 08:24 UTC
