### ISSUE TITLE
sib imports cause nextjs build to fail

### ISSUE THREAD

**Issue by anmolarora1** [sendinblue/APIv3-typescript-library#33] opened 2021-07-09 07:43 UTC
We're trying to use `sib-api-v3-typescript` in our nextjs app but it results in build failure due to typescript compilation errors. This is probably due to the way imports are handled within the package, which isn't compatible with `esnext` syntax (needed for dynamic imports)

![Screenshot 2021-07-09 at 1 05 27 PM](https://user-images.githubusercontent.com/7765764/125042423-6c90d480-e0b7-11eb-9bc1-546571ae915d.png)

Any suggestions would be highly appreciated.

**Comment by aayush-sib** [comment] 2021-07-09 10:14
Hi @anmolarora1 

I have released a beta tag https://www.npmjs.com/package/sib-api-v3-typescript/v/2.2.3-beta.0 for this. Can you please check if this is working well on your side?

**Comment by anmolarora1** [comment] 2021-07-09 14:03
Thanks, @aayush-sib 
Found out another similar issue related to TS exports
![Screenshot 2021-07-09 at 7 30 46 PM](https://user-images.githubusercontent.com/7765764/125089925-69fca200-e0ec-11eb-83b4-3ceaa09f05d9.png)

**Comment by aayush-sib** [comment] 2021-07-09 14:09
Yes @anmolarora1 the issue is already open, if it works for you then I can release the new change.

Can you please confirm if the new beta release worked for you?

**Comment by anmolarora1** [comment] 2021-07-09 14:11
> Yes @anmolarora1 the issue is already open, if it works for you then I can release the new change.
> 
> Can you please confirm if the new beta release worked for you?

No, it didn't. I issue that I [mentioned above](https://github.com/sendinblue/APIv3-typescript-library/issues/33#issuecomment-877213197) describes the build error.

**Comment by aayush-sib** [comment] 2021-07-09 14:24
>No, it didn't. I issue that I mentioned above describes the build error.

Ahh, sorry I looked at the wrong image. Let me check it

**Comment by aayush-sib** [comment] 2021-07-09 14:29
@anmolarora1 Are you using `isolatedModules` in your config? If you are using it can you try removing it and building again?

**Comment by anmolarora1** [comment] 2021-07-12 14:55
@aayush-sib It is mandatory for using babel so we can't remove that.

**Comment by aayush-sib** [comment] 2021-07-13 07:57
Hi @anmolarora1

I have released a beta tag https://www.npmjs.com/package/sib-api-v3-typescript/v/2.2.3-beta.1 for this. Can you please check if this is working well on your side?

**Comment by anmolarora1** [comment] 2021-07-14 06:39
Thanks for the update, @aayush-sib. 
This build seems to work well. However, I can't find it under the [official releases](https://github.com/sendinblue/APIv3-typescript-library/releases) of your repo. Can you share a tentative time by which it'd be published as an official release or as a part of your next release?

**Comment by aayush-sib** [comment] 2021-07-14 06:58
Hi @anmolarora1 
Thanks for the update, I didn't release it in the official releases because it was for testing purposes only. I will soon release it as an official release. By that time you can use this beta tag https://www.npmjs.com/package/sib-api-v3-typescript/v/2.2.3-beta.1.

**Comment by anmolarora1** [comment] 2021-07-26 13:52
Hi @aayush-sib, we discovered that the beta tag you shared fixes the build, but the functionality breaks, however. We're not able to add/remove contacts from our lists after updating to this build. 
Can you please confirm if you guys are planning to release a tested version anytime soon?

**Comment by aayush-sib** [comment] 2021-07-30 06:18
Hi @anmolarora1 
I am not able to reproduce the error at my end. Can you please share the script? 

Also, we will soon release the tested version, there are some changes going on at our end.

**Comment by TomEbeyer** [comment] 2021-08-12 16:30
I encounter the same issue. The beta script does fix the build, but it functionally breaks adding/removing contacts to our list. No feedback as to why it's breaking, though. Can you please test and confirm on your end @aayush-sib?

**Comment by aayush-sib** [comment] 2021-08-13 04:48
Hi @TomEbeyer 

I am not able to replicate the issue at my end. It will be great if you can share the error you are getting and the script you are using for the same.

**Comment by TomEbeyer** [comment] 2021-08-13 13:52
No error message to show when using the beta tag. We build successfully, but functionally we're not able to add or delete contacts. Here are some more details about the script:

`  const initService = async () => {
    if (!sendInBlue) {
      sendInBlue = await import('sib-api-v3-typescript')
    }
    if (!apiInstance) {
      apiInstance = new sendInBlue.ContactsApi()
    }
    apiInstance.setApiKey(sendInBlue.TransactionalEmailsApiApiKeys.apiKey, config.emailConfig.auth.api_key!)
  }`



`        const { body } = await apiInstance.getContactInfo(emailId)
        return body.listIds.indexOf(listId) !== -1
      } catch (error) {
        if (createContactIfMissing && (error.statusCode === 404 || error.statusMessage === 'Not Found')) {
          try {
            const contact = new sendInBlue.CreateContact({ email: emailId })
            contact.email = emailId
            contact.listIds = [listId]
            const { body } = await apiInstance.createContact(contact)
            return !!body.id
          } catch (error) {
            logger.error(`problem while creating contact ${emailId} - ${error.statusMessage} - ${error.message}`)
            return { error }
          }
        }`

**Comment by aayush-sib** [comment] 2021-08-13 15:15
Hi @TomEbeyer 
Can you try with `apiInstance.setApiKey(sendInBlue.ContactsApiApiKeys.apiKey, 'xxx');`

**Comment by anmolarora1** [comment] 2021-08-16 13:36
Hi @aayush-sib 


We're still getting the same error. Just to be clear, it's a `400` with the status message `BAD REQUEST`. There's not enough information in the response body to debug to debut it so we can provide a screenshot for that if you want. 
Also, here's how the code looks like - 


```
const contactEmails = new sendInBlue.AddContactToList()

contactEmails.emails = ['testuser@testmail.com']

const { body, response } = await apiInstance.addContactToList(listId, contactEmails)
```

the API instance is created using this -

```
new sendInBlue.ContactsApi()
```

we tried setting the keys both ways -

```
 apiInstance.setApiKey(sendInBlue.ContactsApiApiKeys.apiKey, config.emailConfig.auth.api_key!)
```
and,
```
 apiInstance.setApiKey(sendInBlue.TransactionalEmailsApiApiKeys.apiKey, config.emailConfig.auth.api_key!)
```

The latter works perfectly with `2.2.2` but fails with the beta version that you've shared


We're running `createContact` and `addContactToList` on the same API instance, which could be causing this issue but it isn't clear from the SIB docs whether that's correct or not.

**Comment by aayush-sib** [comment] 2021-08-20 05:40
Hi @anmolarora1 

Can you try capturing the error message through `error.response.body`?

**Comment by omawang** [comment] 2021-09-01 08:15
Hi @aayush-sib 
I got the same issue here when tried to call `await apiInstance.getContactInfo('john@app.com')`. Then I try to capture the error message, I found this.

```
{
  errorGetContactInfo: {
    response: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [ClientRequest],
      request: [Request],
      toJSON: [Function: responseToJSON],
      caseless: [Caseless],
      body: [Object],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    body: GetExtendedContactDetails {
      email: undefined,
      id: undefined,
      emailBlacklisted: undefined,
      smsBlacklisted: undefined,
      createdAt: undefined,
      modifiedAt: undefined,
      listIds: undefined,
      listUnsubscribed: undefined,
      attributes: undefined,
      statistics: undefined
    }
  }
}
```

seems like the baseUrl got an empty string.

**Comment by aayush-sib** [comment] 2021-09-06 12:02
Hi @omawang 
It seems like the contact doesn’t exist in your account.

**Comment by MysticEarth** [comment] 2021-11-08 18:12
Any news/estimate on when this issue will be fixed? I recently moved to `strict: true` and have this error breaking builds as well :-(

**Comment by aayush-sib** [comment] 2021-11-08 18:52
Hi @MysticEarth 
Which version of sdk are you using?

**Comment by MysticEarth** [comment] 2021-11-08 18:53
I was using `2.2.2`. After trying `2.2.3-beta.1` the errors disappeared.

**Comment by aayush-sib** [comment] 2021-11-08 18:57
Can you try with this sdk https://www.npmjs.com/package/@sendinblue/client?

**Comment by MysticEarth** [comment] 2021-11-08 19:13
👍🏻 Works!

Although the beta for *this* repository fixed build errors but, as mentioned by others, breaks functionality (delivering transactional email in my case).

Switching to `@sendinblue/client` solved ALL issues.

**Comment by aayush-sib** [comment] 2021-11-08 19:16
Thanks for the confirmation @MysticEarth
Yes we did some changes now it will available under `@sendinblue/client`. We have updated the readme of the project also 😄

**Comment by jmccarthy92** [comment] 2021-11-09 16:32
> Thanks for the confirmation @MysticEarth Yes we did some changes now it will be available under `@sendinblue/client`. We have updated the readme of the project also 😄

You may want to mark the following page as deprecated and link it to the updated npm package page: https://www.npmjs.com/package/sib-api-v3-typescript

**Closed** 2022-09-21 10:37 UTC
